version: '3'

services:
  node12:
    build: ./
    volumes:
      - .:/workspace:cached
      - node_modules:/workspace/node_modules
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  node_modules: {}
